// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOyARF57qlpa-xJIxa3EkCi3HuGZsA2o',
    appId: '1:608831631131:web:aa8050fb2ef9cb5208adbe',
    messagingSenderId: '608831631131',
    projectId: 'signin-bismillah',
    authDomain: 'signin-bismillah.firebaseapp.com',
    storageBucket: 'signin-bismillah.appspot.com',
    measurementId: 'G-CK3R4ZWLKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbKNt20WgdILzG-ef36zivZikWkTl--w',
    appId: '1:608831631131:android:3b6f18f3b03070f708adbe',
    messagingSenderId: '608831631131',
    projectId: 'signin-bismillah',
    storageBucket: 'signin-bismillah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkV1kwFYhW-189JeXqmMKu8X8fpgGRDU',
    appId: '1:608831631131:ios:666aa2bcac0177ad08adbe',
    messagingSenderId: '608831631131',
    projectId: 'signin-bismillah',
    storageBucket: 'signin-bismillah.appspot.com',
    iosClientId: '608831631131-iat8jqbm7b4vhi6ijuk1unovmkg6aook.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFiks2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlkV1kwFYhW-189JeXqmMKu8X8fpgGRDU',
    appId: '1:608831631131:ios:666aa2bcac0177ad08adbe',
    messagingSenderId: '608831631131',
    projectId: 'signin-bismillah',
    storageBucket: 'signin-bismillah.appspot.com',
    iosClientId: '608831631131-iat8jqbm7b4vhi6ijuk1unovmkg6aook.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFiks2',
  );
}
